name: ci
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Format
        run: make fmt

      - name: Test
        run: make test

      - name: Build
        run: make build
  
      - uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        with:
          name: discordo_${{ runner.os }}_${{ runner.arch }}
          path: |
            discordo
            discordo.exe
